### PR TITLE
add "use system clipboard" option

### PR DESCRIPTION
**Pull request by suan**

### CODE REVIEW

**Comment by suan** [comment]
Please hold off on this a second, I forgot some of the unfortunate nuances around Vim system clipboard integration. I have to add some checks (and more caveats :frowning: )

**Comment by suan** [comment]
Should now work in both Linux and OSX if the correct Vim is installed.

**Comment by aam1r** [comment]
Great idea! This works really well with MacVim (or standalone vim if it is built with +clipboard). Do you think this should be a default option?

**Comment by suan** [comment]
I think most people would want this functionality but are unaware of it.
Can't imagine many people using the hassle that is vim registers. So yeah
making it enabled by default is a good idea.

**Pull request merged**
